source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "webrick"
gem "kramdown-parser-gfm", "~> 1.1"
gem "rouge"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
